Repository Parnab03/WallGodds, pull requests merged in 2025-04, with the labels that each got.

#78 Added a new wallpaper
  Wallpapers/Mobile/Arushi_74.jpg
  Wallpapers/Mobile/Arushi_Design.jpg
Labels: apertre2.0, doc

#86 fix:alignment of mobile gallary
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/DarkIcon.svg
  Frontend/public/Vector.svg
  Frontend/src/Components/CommonModule/NavBarModule/NavBar.module.css
  Frontend/src/Components/GalleryModule/Gallery.module.css
  Frontend/src/Components/GalleryModule/MobileSection/ImgCardsMobile/ImgCard.jsx
  Frontend/src/Components/GalleryModule/MobileSection/ImgCardsMobile/ImgCard.module.css
  Frontend/src/Components/GalleryModule/MobileSection/Mobile.jsx
  Frontend/src/Components/GalleryModule/MobileSection/Mobile.module.css
  Frontend/src/Components/GalleryModule/SideBarModule/SideBar.jsx
  Frontend/src/Components/GalleryModule/SideBarModule/SideBar.module.css
  Frontend/src/Components/ThemeModule/ThemeToggle.jsx
Labels: medium, apertre2.0

#90 Fixed changes in error404 page
  Frontend/src/Components/ErrorModule/Error404.jsx
  Frontend/src/Components/ErrorModule/Error404.module.css
Labels: easy, apertre2.0

#92 feat: About us page completed
  Frontend/package-lock.json
  Frontend/public/Arrow-know-more.png
  Frontend/public/Our Mission.png
  Frontend/public/core-values.png
  Frontend/public/discord-icon.png
  Frontend/public/github-icon.png
  Frontend/public/inspiration.png
  Frontend/public/let’s work together.png
  Frontend/public/linkedin-icon.png
  Frontend/public/milestone.png
  Frontend/public/mission.png
  Frontend/src/App.jsx
  Frontend/src/Components/AboutModule/Aboutus.jsx
  Frontend/src/Components/AboutModule/Aboutus.module.css
  Frontend/src/Components/AboutModule/Footer.jsx
  Frontend/src/Components/CommonModule/NavBarModule/NavBar.jsx
  Frontend/src/Components/CommonModule/NavBarModule/NavBar.module.css
Labels: hard, apertre2.0

#95 Mobile Gallery UI fixed in all screen widths
  Frontend/src/Components/CommonModule/NavBarModule/NavBar.module.css
  Frontend/src/Components/GalleryModule/Gallery.module.css
  Frontend/src/Components/GalleryModule/SideBarModule/SideBar.module.css
Labels: medium, apertre2.0
